image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  YAZ_VERSION: 5.27.2
  PAZPAR2_VERSION: 1.14.0
  
services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
build-master:
  only:
    - master
  script:
    - docker build --build-arg YAZ_VERSION=${YAZ_VERSION} --build-arg PAZPAR2_VERSION=${PAZPAR2_VERSION} -f Dockerfile -t "${CI_REGISTRY_IMAGE}/pazpar2:${PAZPAR2_VERSION}-alpine" .
    - docker push "${CI_REGISTRY_IMAGE}/pazpar2:${PAZPAR2_VERSION}-alpine"
  except:
    - tags

trigger_build:
  stage: deploy
  script:
    - "apk add --no-cache curl"
    - "curl -X POST -F token=0be37a72f0aa47617ce5e541f20cfb -F ref=master https://gitlab.gwdg.de/api/v4/projects/8486/trigger/pipeline"
  only:
    - master
  except:
    - tags